spring.application.name=Full_Stack_Food_Delivery_App

spring.data.mongodb.uri=mongodb://localhost:27017/FoodApp
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rdjironman300@gmail.com
spring.mail.password=axqzekifijoutdpt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.address=0.0.0.0
server.port=8080


#razorpay.key.id=rzp_test_xxxxxxxxxx
#razorpay.key.secret=xxxxxxxxxxxxxxxx



